export interface PortageItem {
    id: string;
    domain: 'socializacao' | 'linguagem' | 'cognicao' | 'autocuidados' | 'motor';
    rangeIndex: number;
    text: string;
}

export type ItemResponse = 'sim' | 'ajuda' | 'nao' | null;

export const PORTAGE_ITEMS: PortageItem[] = [
  { id:'s0_01', domain:'socializacao', rangeIndex:0, text:'Sorri em resposta ao sorriso do adulto' },
  { id:'s0_02', domain:'socializacao', rangeIndex:0, text:'Reconhece a voz da mãe/cuidador principal' },
  { id:'s0_03', domain:'socializacao', rangeIndex:0, text:'Chora de formas diferentes (fome, dor, sono)' },
  { id:'s0_04', domain:'socializacao', rangeIndex:0, text:'Imita expressões faciais simples' },
  { id:'s0_05', domain:'socializacao', rangeIndex:0, text:'Brinca de esconde-esconde (peek-a-boo)' },
  { id:'s0_06', domain:'socializacao', rangeIndex:0, text:'Estende os braços para ser pego' },
  { id:'s0_07', domain:'socializacao', rangeIndex:0, text:'Responde ao próprio nome' },
  { id:'s0_08', domain:'socializacao', rangeIndex:0, text:'Demonstra preferência por familiares' },
  { id:'s0_09', domain:'socializacao', rangeIndex:0, text:'Mostra estranhamento com desconhecidos' },
  { id:'s0_10', domain:'socializacao', rangeIndex:0, text:'Acena com a mão (tchau)' },
  { id:'s0_11', domain:'socializacao', rangeIndex:0, text:'Bate palmas quando solicitado' },
  { id:'s0_12', domain:'socializacao', rangeIndex:0, text:'Imita gestos simples do adulto' },
  { id:'s0_13', domain:'socializacao', rangeIndex:0, text:'Busca atenção do adulto vocalizando' },
  { id:'s0_14', domain:'socializacao', rangeIndex:0, text:'Sorri espontaneamente para pessoas familiares' },
  { id:'s0_15', domain:'socializacao', rangeIndex:0, text:'Demonstra prazer em interações sociais' },
  { id:'s0_16', domain:'socializacao', rangeIndex:0, text:'Usa o adulto como base segura para explorar' },
  { id:'s0_17', domain:'socializacao', rangeIndex:0, text:'Segura objetos e os oferece ao adulto' },
  { id:'s0_18', domain:'socializacao', rangeIndex:0, text:'Participa de brincadeiras de causa e efeito' },
  { id:'s0_19', domain:'socializacao', rangeIndex:0, text:'Chama atenção apontando com o dedo' },
  { id:'s0_20', domain:'socializacao', rangeIndex:0, text:'Imita atividades simples do cotidiano' },
  { id:'s0_21', domain:'socializacao', rangeIndex:0, text:'Demonstra afeto por pessoas familiares' },
  { id:'s0_22', domain:'socializacao', rangeIndex:0, text:'Reage quando o adulto se afasta' },
  { id:'s0_23', domain:'socializacao', rangeIndex:0, text:'Brinca sozinho por alguns minutos' },
  { id:'s0_24', domain:'socializacao', rangeIndex:0, text:'Observa outras crianças com interesse' },
  { id:'s0_25', domain:'socializacao', rangeIndex:0, text:'Compartilha brinquedos com o adulto' },
  { id:'s0_26', domain:'socializacao', rangeIndex:0, text:'Segue o olhar do adulto' },
  { id:'s0_27', domain:'socializacao', rangeIndex:0, text:'Responde a elogios com sorriso ou vocalização' },
  { id:'s0_28', domain:'socializacao', rangeIndex:0, text:'Demonstra ciúmes quando o adulto dá atenção a outro' },
  { id:'s1_01', domain:'socializacao', rangeIndex:1, text:'Brinca ao lado de outras crianças (jogo paralelo)' },
  { id:'s1_02', domain:'socializacao', rangeIndex:1, text:'Imita ações simples de outras crianças' },
  { id:'s1_03', domain:'socializacao', rangeIndex:1, text:'Chama adulto para mostrar algo interessante' },
  { id:'s1_04', domain:'socializacao', rangeIndex:1, text:'Abraça e beija pessoas familiares espontaneamente' },
  { id:'s1_05', domain:'socializacao', rangeIndex:1, text:'Demonstra independência explorando o ambiente' },
  { id:'s1_06', domain:'socializacao', rangeIndex:1, text:'Participa de brincadeiras de imitação' },
  { id:'s1_07', domain:'socializacao', rangeIndex:1, text:'Obedece a pedidos simples com gesto' },
  { id:'s1_08', domain:'socializacao', rangeIndex:1, text:'Demonstra orgulho ao conseguir fazer algo' },
  { id:'s1_09', domain:'socializacao', rangeIndex:1, text:'Indica necessidades apontando ou vocalizando' },
  { id:'s1_10', domain:'socializacao', rangeIndex:1, text:'Brinca de faz-de-conta simples' },
  { id:'s1_11', domain:'socializacao', rangeIndex:1, text:'Defende seus brinquedos de outras crianças' },
  { id:'s1_12', domain:'socializacao', rangeIndex:1, text:'Reage a proibições (para ou chora)' },
  { id:'s1_13', domain:'socializacao', rangeIndex:1, text:'Demonstra carinho com bonecas ou pelúcias' },
  { id:'s1_14', domain:'socializacao', rangeIndex:1, text:'Explora ambiente novo com segurança' },
  { id:'s1_15', domain:'socializacao', rangeIndex:1, text:'Busca conforto quando machucado ou assustado' },
  { id:'s1_16', domain:'socializacao', rangeIndex:1, text:'Participa de brincadeiras em grupo simples' },
  { id:'s2_01', domain:'socializacao', rangeIndex:2, text:'Divide brinquedos com colegas quando solicitado' },
  { id:'s2_02', domain:'socializacao', rangeIndex:2, text:'Aguarda sua vez em brincadeiras simples' },
  { id:'s2_03', domain:'socializacao', rangeIndex:2, text:'Segue regras simples de jogos' },
  { id:'s2_04', domain:'socializacao', rangeIndex:2, text:'Brinca cooperativamente com outras crianças' },
  { id:'s2_05', domain:'socializacao', rangeIndex:2, text:'Demonstra empatia (consola colega que chora)' },
  { id:'s2_06', domain:'socializacao', rangeIndex:2, text:'Faz amizade com crianças da mesma idade' },
  { id:'s2_07', domain:'socializacao', rangeIndex:2, text:'Ajuda em tarefas domésticas simples' },
  { id:'s2_08', domain:'socializacao', rangeIndex:2, text:'Pede desculpas quando faz algo errado' },
  { id:'s3_01', domain:'socializacao', rangeIndex:3, text:'Brinca em grupo com regras básicas' },
  { id:'s3_02', domain:'socializacao', rangeIndex:3, text:'Tem amigo preferido' },
  { id:'s3_03', domain:'socializacao', rangeIndex:3, text:'Entende o que é "meu" e "seu"' },
  { id:'s3_04', domain:'socializacao', rangeIndex:3, text:'Conta experiências pessoais simples' },
  { id:'s3_05', domain:'socializacao', rangeIndex:3, text:'Defende a si mesmo verbalmente' },
  { id:'s3_06', domain:'socializacao', rangeIndex:3, text:'Respeita os sentimentos dos outros' },
  { id:'s3_07', domain:'socializacao', rangeIndex:3, text:'Participa de atividades em grupo na escola' },
  { id:'s3_08', domain:'socializacao', rangeIndex:3, text:'Segue regras de convivência social' },
  { id:'s3_09', domain:'socializacao', rangeIndex:3, text:'Distingue comportamentos adequados e inadequados' },
  { id:'s3_10', domain:'socializacao', rangeIndex:3, text:'Demonstra preferências em brincadeiras' },
  { id:'s3_11', domain:'socializacao', rangeIndex:3, text:'Aceita perder em jogos simples' },
  { id:'s3_12', domain:'socializacao', rangeIndex:3, text:'Cumprimenta pessoas conhecidas' },
  { id:'s4_01', domain:'socializacao', rangeIndex:4, text:'Participa de jogos cooperativos' },
  { id:'s4_02', domain:'socializacao', rangeIndex:4, text:'Respeita a autoridade do adulto' },
  { id:'s4_03', domain:'socializacao', rangeIndex:4, text:'Lida bem com frustrações simples' },
  { id:'s4_04', domain:'socializacao', rangeIndex:4, text:'Demonstra responsabilidade com tarefas' },
  { id:'s4_05', domain:'socializacao', rangeIndex:4, text:'Entende e segue regras da sala de aula' },
  { id:'s4_06', domain:'socializacao', rangeIndex:4, text:'Faz escolhas e defende sua opinião' },
  { id:'s4_07', domain:'socializacao', rangeIndex:4, text:'Demonstra autocontrole em situações de conflito' },
  { id:'s4_08', domain:'socializacao', rangeIndex:4, text:'Respeita diferenças entre colegas' },
  { id:'s4_09', domain:'socializacao', rangeIndex:4, text:'Participa de atividades de grupo na comunidade' },
  { id:'s5_01', domain:'socializacao', rangeIndex:5, text:'Demonstra comportamento adequado em público' },
  { id:'s5_02', domain:'socializacao', rangeIndex:5, text:'Resolve conflitos com palavras' },
  { id:'s5_03', domain:'socializacao', rangeIndex:5, text:'Faz e mantém amizades' },
  { id:'s5_04', domain:'socializacao', rangeIndex:5, text:'Demonstra senso de responsabilidade' },
  { id:'s5_05', domain:'socializacao', rangeIndex:5, text:'Participa ativamente em sala de aula' },
  { id:'s5_06', domain:'socializacao', rangeIndex:5, text:'Compreende regras sociais complexas' },
  { id:'s5_07', domain:'socializacao', rangeIndex:5, text:'Demonstra empatia e solidariedade' },
  { id:'s5_08', domain:'socializacao', rangeIndex:5, text:'Lida bem com mudanças de rotina' },
  { id:'s5_09', domain:'socializacao', rangeIndex:5, text:'Defende seus direitos respeitosamente' },
  { id:'s5_10', domain:'socializacao', rangeIndex:5, text:'Demonstra autonomia social adequada à idade' },
  { id:'s5_11', domain:'socializacao', rangeIndex:5, text:'Coopera em projetos coletivos' },
  { id:'l0_01', domain:'linguagem', rangeIndex:0, text:'Vocaliza sons para expressar prazer ou desprazer' },
  { id:'l0_02', domain:'linguagem', rangeIndex:0, text:'Reage ao som virando a cabeça' },
  { id:'l0_03', domain:'linguagem', rangeIndex:0, text:'Balbucia sílabas repetidas (ma-ma, ba-ba)' },
  { id:'l0_04', domain:'linguagem', rangeIndex:0, text:'Imita sons produzidos pelo adulto' },
  { id:'l0_05', domain:'linguagem', rangeIndex:0, text:'Usa gestos para comunicar (apontar, acenar)' },
  { id:'l0_06', domain:'linguagem', rangeIndex:0, text:'Compreende "não" e para a ação' },
  { id:'l0_07', domain:'linguagem', rangeIndex:0, text:'Responde ao próprio nome' },
  { id:'l0_08', domain:'linguagem', rangeIndex:0, text:'Produz variações de entonação' },
  { id:'l0_09', domain:'linguagem', rangeIndex:0, text:'Diz pelo menos uma palavra com significado' },
  { id:'l0_10', domain:'linguagem', rangeIndex:0, text:'Entende palavras familiares simples' },
  { id:'l1_01', domain:'linguagem', rangeIndex:1, text:'Usa 10 ou mais palavras diferentes' },
  { id:'l1_02', domain:'linguagem', rangeIndex:1, text:'Combina duas palavras (mamã água)' },
  { id:'l1_03', domain:'linguagem', rangeIndex:1, text:'Nomeia objetos do cotidiano' },
  { id:'l1_04', domain:'linguagem', rangeIndex:1, text:'Usa palavras para expressar necessidades' },
  { id:'l1_05', domain:'linguagem', rangeIndex:1, text:'Aponta partes do corpo quando solicitado' },
  { id:'l1_06', domain:'linguagem', rangeIndex:1, text:'Compreende frases simples com ação' },
  { id:'l1_07', domain:'linguagem', rangeIndex:1, text:'Usa "não" com intencionalidade comunicativa' },
  { id:'l1_08', domain:'linguagem', rangeIndex:1, text:'Nomeia figuras em livros de imagens' },
  { id:'l1_09', domain:'linguagem', rangeIndex:1, text:'Faz perguntas simples (cadê? o que é?)' },
  { id:'l1_10', domain:'linguagem', rangeIndex:1, text:'Usa pronomes (eu, meu)' },
  { id:'l1_11', domain:'linguagem', rangeIndex:1, text:'Repete palavras ditas pelo adulto' },
  { id:'l1_12', domain:'linguagem', rangeIndex:1, text:'Compreende preposições simples (em cima, embaixo)' },
  { id:'l1_13', domain:'linguagem', rangeIndex:1, text:'Usa frases de 2 a 3 palavras' },
  { id:'l1_14', domain:'linguagem', rangeIndex:1, text:'Nomeia animais domésticos comuns' },
  { id:'l1_15', domain:'linguagem', rangeIndex:1, text:'Descreve ações em figuras' },
  { id:'l1_16', domain:'linguagem', rangeIndex:1, text:'Canta partes de músicas conhecidas' },
  { id:'l1_17', domain:'linguagem', rangeIndex:1, text:'Usa artigos definidos e indefinidos' },
  { id:'l1_18', domain:'linguagem', rangeIndex:1, text:'Compreende ordens com duas etapas' },
  { id:'l2_01', domain:'linguagem', rangeIndex:2, text:'Usa frases com 3 a 4 palavras' },
  { id:'l2_02', domain:'linguagem', rangeIndex:2, text:'Conta histórias simples com sequência' },
  { id:'l2_03', domain:'linguagem', rangeIndex:2, text:'Faz perguntas com "por quê" e "quando"' },
  { id:'l2_04', domain:'linguagem', rangeIndex:2, text:'Usa plural regularmente' },
  { id:'l2_05', domain:'linguagem', rangeIndex:2, text:'Nomeia cores primárias' },
  { id:'l2_06', domain:'linguagem', rangeIndex:2, text:'Descreve experiências recentes' },
  { id:'l2_07', domain:'linguagem', rangeIndex:2, text:'Usa verbos no passado corretamente' },
  { id:'l2_08', domain:'linguagem', rangeIndex:2, text:'Entende conceitos espaciais (dentro, fora, entre)' },
  { id:'l2_09', domain:'linguagem', rangeIndex:2, text:'Usa frases negativas corretamente' },
  { id:'l2_10', domain:'linguagem', rangeIndex:2, text:'Repete sequências de 3 palavras' },
  { id:'l3_01', domain:'linguagem', rangeIndex:3, text:'Usa frases complexas com conjunções' },
  { id:'l3_02', domain:'linguagem', rangeIndex:3, text:'Narra histórias com início, meio e fim' },
  { id:'l3_03', domain:'linguagem', rangeIndex:3, text:'Compreende e usa conceitos de tempo' },
  { id:'l3_04', domain:'linguagem', rangeIndex:3, text:'Define palavras simples' },
  { id:'l3_05', domain:'linguagem', rangeIndex:3, text:'Usa linguagem para resolver problemas' },
  { id:'l3_06', domain:'linguagem', rangeIndex:3, text:'Compreende piadas simples' },
  { id:'l3_07', domain:'linguagem', rangeIndex:3, text:'Reconhece rimas' },
  { id:'l3_08', domain:'linguagem', rangeIndex:3, text:'Usa pronomes pessoais corretamente' },
  { id:'l3_09', domain:'linguagem', rangeIndex:3, text:'Segue instruções com 3 etapas' },
  { id:'l3_10', domain:'linguagem', rangeIndex:3, text:'Descreve diferenças entre objetos' },
  { id:'l3_11', domain:'linguagem', rangeIndex:3, text:'Usa linguagem para fazer amigos' },
  { id:'l3_12', domain:'linguagem', rangeIndex:3, text:'Compreende categorias semânticas' },
  { id:'l3_13', domain:'linguagem', rangeIndex:3, text:'Usa verbos auxiliares corretamente' },
  { id:'l3_14', domain:'linguagem', rangeIndex:3, text:'Responde a perguntas de compreensão de texto oral' },
  { id:'l3_15', domain:'linguagem', rangeIndex:3, text:'Conta até 10 objetos' },
  { id:'l3_16', domain:'linguagem', rangeIndex:3, text:'Nomeia letras do alfabeto' },
  { id:'l3_17', domain:'linguagem', rangeIndex:3, text:'Identifica palavra inicial de frases' },
  { id:'l3_18', domain:'linguagem', rangeIndex:3, text:'Usa linguagem figurada simples' },
  { id:'l3_19', domain:'linguagem', rangeIndex:3, text:'Descreve eventos passados com detalhes' },
  { id:'l3_20', domain:'linguagem', rangeIndex:3, text:'Compreende conceitos comparativos (maior, menor)' },
  { id:'l3_21', domain:'linguagem', rangeIndex:3, text:'Usa linguagem para negociar com pares' },
  { id:'l3_22', domain:'linguagem', rangeIndex:3, text:'Nomeia formas geométricas básicas' },
  { id:'l3_23', domain:'linguagem', rangeIndex:3, text:'Descreve função de objetos do cotidiano' },
  { id:'l3_24', domain:'linguagem', rangeIndex:3, text:'Compreende e usa antônimos simples' },
  { id:'l4_01', domain:'linguagem', rangeIndex:4, text:'Lê palavras simples' },
  { id:'l4_02', domain:'linguagem', rangeIndex:4, text:'Compreende texto lido em voz alta' },
  { id:'l4_03', domain:'linguagem', rangeIndex:4, text:'Usa linguagem para argumentar' },
  { id:'l4_04', domain:'linguagem', rangeIndex:4, text:'Escreve palavras simples' },
  { id:'l4_05', domain:'linguagem', rangeIndex:4, text:'Identifica sílabas em palavras' },
  { id:'l4_06', domain:'linguagem', rangeIndex:4, text:'Compreende metáforas simples' },
  { id:'l4_07', domain:'linguagem', rangeIndex:4, text:'Usa vocabulário adequado ao contexto' },
  { id:'l4_08', domain:'linguagem', rangeIndex:4, text:'Segue conversas com múltiplos participantes' },
  { id:'l4_09', domain:'linguagem', rangeIndex:4, text:'Conta histórias com detalhes e coerência' },
  { id:'l4_10', domain:'linguagem', rangeIndex:4, text:'Compreende ironias simples' },
  { id:'l4_11', domain:'linguagem', rangeIndex:4, text:'Usa conjunções causais e temporais' },
  { id:'l4_12', domain:'linguagem', rangeIndex:4, text:'Adapta linguagem ao interlocutor' },
  { id:'l4_13', domain:'linguagem', rangeIndex:4, text:'Nomeia e usa conceitos matemáticos básicos' },
  { id:'l4_14', domain:'linguagem', rangeIndex:4, text:'Compreende instruções escritas simples' },
  { id:'l4_15', domain:'linguagem', rangeIndex:4, text:'Usa linguagem para planejar ações futuras' },
  { id:'l5_01', domain:'linguagem', rangeIndex:5, text:'Lê fluentemente textos simples' },
  { id:'l5_02', domain:'linguagem', rangeIndex:5, text:'Escreve frases completas com coerência' },
  { id:'l5_03', domain:'linguagem', rangeIndex:5, text:'Compreende textos narrativos e informativos' },
  { id:'l5_04', domain:'linguagem', rangeIndex:5, text:'Usa linguagem formal em contextos adequados' },
  { id:'l5_05', domain:'linguagem', rangeIndex:5, text:'Faz inferências a partir de textos' },
  { id:'l5_06', domain:'linguagem', rangeIndex:5, text:'Usa vocabulário rico e variado' },
  { id:'l5_07', domain:'linguagem', rangeIndex:5, text:'Produz textos curtos com estrutura clara' },
  { id:'l5_08', domain:'linguagem', rangeIndex:5, text:'Compreende e usa linguagem figurada' },
  { id:'l5_09', domain:'linguagem', rangeIndex:5, text:'Identifica ideia principal de um texto' },
  { id:'l5_10', domain:'linguagem', rangeIndex:5, text:'Usa linguagem para resolver conflitos verbalmente' },
  { id:'l5_11', domain:'linguagem', rangeIndex:5, text:'Domina concordância verbal e nominal básica' },
  { id:'l5_12', domain:'linguagem', rangeIndex:5, text:'Participa de debates simples com argumentos' },
  { id:'l5_13', domain:'linguagem', rangeIndex:5, text:'Relata eventos com sequência lógica e temporal' },
  { id:'l5_14', domain:'linguagem', rangeIndex:5, text:'Compreende múltiplos significados de palavras' },
  { id:'c0_01', domain:'cognicao', rangeIndex:0, text:'Segue objeto em movimento com os olhos' },
  { id:'c0_02', domain:'cognicao', rangeIndex:0, text:'Busca objeto escondido parcialmente' },
  { id:'c0_03', domain:'cognicao', rangeIndex:0, text:'Imita ações simples com objetos' },
  { id:'c0_04', domain:'cognicao', rangeIndex:0, text:'Explora objetos com mãos e boca' },
  { id:'c0_05', domain:'cognicao', rangeIndex:0, text:'Demonstra permanência do objeto' },
  { id:'c0_06', domain:'cognicao', rangeIndex:0, text:'Encaixa formas simples (círculo, quadrado)' },
  { id:'c0_07', domain:'cognicao', rangeIndex:0, text:'Resolve problemas simples por tentativa e erro' },
  { id:'c0_08', domain:'cognicao', rangeIndex:0, text:'Combina dois objetos em brincadeira funcional' },
  { id:'c0_09', domain:'cognicao', rangeIndex:0, text:'Reconhece figuras familiares em fotos' },
  { id:'c0_10', domain:'cognicao', rangeIndex:0, text:'Demonstra antecipação de rotinas' },
  { id:'c0_11', domain:'cognicao', rangeIndex:0, text:'Usa objetos como ferramentas simples' },
  { id:'c0_12', domain:'cognicao', rangeIndex:0, text:'Faz torre com 2 a 3 cubos' },
  { id:'c0_13', domain:'cognicao', rangeIndex:0, text:'Interessa-se por livros de imagens' },
  { id:'c0_14', domain:'cognicao', rangeIndex:0, text:'Empilha objetos por tamanho simples' },
  { id:'c1_01', domain:'cognicao', rangeIndex:1, text:'Combina objetos por cor ou forma' },
  { id:'c1_02', domain:'cognicao', rangeIndex:1, text:'Completa quebra-cabeça de 2 a 3 peças' },
  { id:'c1_03', domain:'cognicao', rangeIndex:1, text:'Demonstra noção de quantidade (mais/menos)' },
  { id:'c1_04', domain:'cognicao', rangeIndex:1, text:'Segue sequência de 2 etapas' },
  { id:'c1_05', domain:'cognicao', rangeIndex:1, text:'Nomeia 5 partes do corpo' },
  { id:'c1_06', domain:'cognicao', rangeIndex:1, text:'Agrupa objetos iguais' },
  { id:'c1_07', domain:'cognicao', rangeIndex:1, text:'Reconhece o que falta em uma figura' },
  { id:'c1_08', domain:'cognicao', rangeIndex:1, text:'Identifica objetos pelo uso' },
  { id:'c1_09', domain:'cognicao', rangeIndex:1, text:'Empilha argolas por tamanho' },
  { id:'c1_10', domain:'cognicao', rangeIndex:1, text:'Copia rabisco e linha vertical' },
  { id:'c2_01', domain:'cognicao', rangeIndex:2, text:'Nomeia e identifica cores primárias' },
  { id:'c2_02', domain:'cognicao', rangeIndex:2, text:'Conta até 5 objetos com correspondência' },
  { id:'c2_03', domain:'cognicao', rangeIndex:2, text:'Completa sequências simples' },
  { id:'c2_04', domain:'cognicao', rangeIndex:2, text:'Compreende conceitos grande/pequeno' },
  { id:'c2_05', domain:'cognicao', rangeIndex:2, text:'Resolve quebra-cabeça de 4 a 6 peças' },
  { id:'c2_06', domain:'cognicao', rangeIndex:2, text:'Classifica objetos por 2 atributos' },
  { id:'c2_07', domain:'cognicao', rangeIndex:2, text:'Identifica formas geométricas básicas' },
  { id:'c2_08', domain:'cognicao', rangeIndex:2, text:'Compreende conceitos temporais (ontem, hoje, amanhã)' },
  { id:'c2_09', domain:'cognicao', rangeIndex:2, text:'Nomeia posições espaciais' },
  { id:'c2_10', domain:'cognicao', rangeIndex:2, text:'Memoriza sequência de 3 itens' },
  { id:'c2_11', domain:'cognicao', rangeIndex:2, text:'Desenha figura humana com 3 partes' },
  { id:'c2_12', domain:'cognicao', rangeIndex:2, text:'Compreende conceito de metade' },
  { id:'c2_13', domain:'cognicao', rangeIndex:2, text:'Resolve analogias simples' },
  { id:'c2_14', domain:'cognicao', rangeIndex:2, text:'Identifica o que é diferente em grupo de objetos' },
  { id:'c2_15', domain:'cognicao', rangeIndex:2, text:'Compreende sequência lógica de histórias' },
  { id:'c2_16', domain:'cognicao', rangeIndex:2, text:'Usa materiais de forma criativa' },
  { id:'c3_01', domain:'cognicao', rangeIndex:3, text:'Conta até 10 com correspondência' },
  { id:'c3_02', domain:'cognicao', rangeIndex:3, text:'Reconhece letras do próprio nome' },
  { id:'c3_03', domain:'cognicao', rangeIndex:3, text:'Completa quebra-cabeça de 10 a 15 peças' },
  { id:'c3_04', domain:'cognicao', rangeIndex:3, text:'Compreende conceitos de adição simples' },
  { id:'c3_05', domain:'cognicao', rangeIndex:3, text:'Ordena sequência de figuras por lógica' },
  { id:'c3_06', domain:'cognicao', rangeIndex:3, text:'Identifica padrões e sequências' },
  { id:'c3_07', domain:'cognicao', rangeIndex:3, text:'Reconhece numerais de 1 a 10' },
  { id:'c3_08', domain:'cognicao', rangeIndex:3, text:'Compreende causa e efeito em situações' },
  { id:'c3_09', domain:'cognicao', rangeIndex:3, text:'Classifica animais por categorias' },
  { id:'c3_10', domain:'cognicao', rangeIndex:3, text:'Copia formas geométricas simples' },
  { id:'c3_11', domain:'cognicao', rangeIndex:3, text:'Descreve diferenças entre imagens' },
  { id:'c3_12', domain:'cognicao', rangeIndex:3, text:'Compreende conceitos de peso e medida' },
  { id:'c3_13', domain:'cognicao', rangeIndex:3, text:'Faz estimativas simples' },
  { id:'c3_14', domain:'cognicao', rangeIndex:3, text:'Identifica erros absurdos em figuras' },
  { id:'c3_15', domain:'cognicao', rangeIndex:3, text:'Memoriza sequência de 4 itens' },
  { id:'c3_16', domain:'cognicao', rangeIndex:3, text:'Compreende conceitos de tempo (horas simples)' },
  { id:'c3_17', domain:'cognicao', rangeIndex:3, text:'Resolve problemas de subtração simples' },
  { id:'c3_18', domain:'cognicao', rangeIndex:3, text:'Copia letras e números isolados' },
  { id:'c3_19', domain:'cognicao', rangeIndex:3, text:'Demonstra raciocínio lógico em jogos' },
  { id:'c3_20', domain:'cognicao', rangeIndex:3, text:'Reconhece dinheiro em situações cotidianas' },
  { id:'c3_21', domain:'cognicao', rangeIndex:3, text:'Compreende conceitos de mais e menos numérico' },
  { id:'c3_22', domain:'cognicao', rangeIndex:3, text:'Planeja ação antes de executar' },
  { id:'c3_23', domain:'cognicao', rangeIndex:3, text:'Identifica letras do alfabeto' },
  { id:'c3_24', domain:'cognicao', rangeIndex:3, text:'Usa estratégias para memorizar informações' },
  { id:'c4_01', domain:'cognicao', rangeIndex:4, text:'Opera com adição e subtração até 10' },
  { id:'c4_02', domain:'cognicao', rangeIndex:4, text:'Lê palavras e frases simples' },
  { id:'c4_03', domain:'cognicao', rangeIndex:4, text:'Compreende conceitos de multiplicação básica' },
  { id:'c4_04', domain:'cognicao', rangeIndex:4, text:'Resolve problemas matemáticos simples' },
  { id:'c4_05', domain:'cognicao', rangeIndex:4, text:'Organiza informações em sequência lógica' },
  { id:'c4_06', domain:'cognicao', rangeIndex:4, text:'Usa estratégias de resolução de problemas' },
  { id:'c4_07', domain:'cognicao', rangeIndex:4, text:'Compreende mapas e plantas simples' },
  { id:'c4_08', domain:'cognicao', rangeIndex:4, text:'Identifica padrões numéricos' },
  { id:'c4_09', domain:'cognicao', rangeIndex:4, text:'Faz inferências lógicas simples' },
  { id:'c4_10', domain:'cognicao', rangeIndex:4, text:'Demonstra memória de trabalho adequada' },
  { id:'c4_11', domain:'cognicao', rangeIndex:4, text:'Compreende frações simples' },
  { id:'c4_12', domain:'cognicao', rangeIndex:4, text:'Classifica e organiza dados simples' },
  { id:'c4_13', domain:'cognicao', rangeIndex:4, text:'Demonstra atenção sustentada em tarefas' },
  { id:'c4_14', domain:'cognicao', rangeIndex:4, text:'Usa raciocínio dedutivo simples' },
  { id:'c4_15', domain:'cognicao', rangeIndex:4, text:'Compreende relações de causa e efeito complexas' },
  { id:'c4_16', domain:'cognicao', rangeIndex:4, text:'Transfere aprendizado para novas situações' },
  { id:'c4_17', domain:'cognicao', rangeIndex:4, text:'Planeja e monitora seu próprio aprendizado' },
  { id:'c4_18', domain:'cognicao', rangeIndex:4, text:'Resolve problemas de forma criativa' },
  { id:'c4_19', domain:'cognicao', rangeIndex:4, text:'Compreende conceitos científicos básicos' },
  { id:'c4_20', domain:'cognicao', rangeIndex:4, text:'Usa tecnologia simples para aprender' },
  { id:'c4_21', domain:'cognicao', rangeIndex:4, text:'Demonstra pensamento abstrato inicial' },
  { id:'c4_22', domain:'cognicao', rangeIndex:4, text:'Compreende textos informativos simples' },
  { id:'c5_01', domain:'cognicao', rangeIndex:5, text:'Opera com as 4 operações básicas' },
  { id:'c5_02', domain:'cognicao', rangeIndex:5, text:'Lê e compreende textos variados' },
  { id:'c5_03', domain:'cognicao', rangeIndex:5, text:'Resolve problemas matemáticos complexos' },
  { id:'c5_04', domain:'cognicao', rangeIndex:5, text:'Demonstra pensamento crítico' },
  { id:'c5_05', domain:'cognicao', rangeIndex:5, text:'Planeja e executa projetos simples' },
  { id:'c5_06', domain:'cognicao', rangeIndex:5, text:'Compreende conceitos científicos elementares' },
  { id:'c5_07', domain:'cognicao', rangeIndex:5, text:'Usa estratégias metacognitivas' },
  { id:'c5_08', domain:'cognicao', rangeIndex:5, text:'Transfere conhecimento entre disciplinas' },
  { id:'c5_09', domain:'cognicao', rangeIndex:5, text:'Demonstra raciocínio lógico-matemático' },
  { id:'c5_10', domain:'cognicao', rangeIndex:5, text:'Compreende conceitos geográficos básicos' },
  { id:'c5_11', domain:'cognicao', rangeIndex:5, text:'Usa múltiplas fontes de informação' },
  { id:'c5_12', domain:'cognicao', rangeIndex:5, text:'Demonstra autonomia no aprendizado' },
  { id:'c5_13', domain:'cognicao', rangeIndex:5, text:'Resolve situações-problema do cotidiano' },
  { id:'c5_14', domain:'cognicao', rangeIndex:5, text:'Compreende e aplica regras gramaticais' },
  { id:'c5_15', domain:'cognicao', rangeIndex:5, text:'Demonstra criatividade e pensamento divergente' },
  { id:'c5_16', domain:'cognicao', rangeIndex:5, text:'Avalia seu próprio desempenho' },
  { id:'c5_17', domain:'cognicao', rangeIndex:5, text:'Compreende conceitos históricos básicos' },
  { id:'c5_18', domain:'cognicao', rangeIndex:5, text:'Organiza e apresenta informações' },
  { id:'c5_19', domain:'cognicao', rangeIndex:5, text:'Demonstra memória de longo prazo eficiente' },
  { id:'c5_20', domain:'cognicao', rangeIndex:5, text:'Usa raciocínio hipotético-dedutivo inicial' },
  { id:'c5_21', domain:'cognicao', rangeIndex:5, text:'Compreende conceitos abstratos básicos' },
  { id:'c5_22', domain:'cognicao', rangeIndex:5, text:'Planeja e gerencia o tempo de estudo' },
  { id:'a0_01', domain:'autocuidados', rangeIndex:0, text:'Suga eficientemente durante a amamentação' },
  { id:'a0_02', domain:'autocuidados', rangeIndex:0, text:'Dorme em ciclos regulares' },
  { id:'a0_03', domain:'autocuidados', rangeIndex:0, text:'Aceita alimentos pastosos sem engasgar' },
  { id:'a0_04', domain:'autocuidados', rangeIndex:0, text:'Segura mamadeira ou copo com apoio' },
  { id:'a0_05', domain:'autocuidados', rangeIndex:0, text:'Demonstra sinais de fome e saciedade' },
  { id:'a0_06', domain:'autocuidados', rangeIndex:0, text:'Colabora no banho (não resiste)' },
  { id:'a0_07', domain:'autocuidados', rangeIndex:0, text:'Estende braços e pernas ao ser vestido' },
  { id:'a0_08', domain:'autocuidados', rangeIndex:0, text:'Segura colher e leva à boca com ajuda' },
  { id:'a0_09', domain:'autocuidados', rangeIndex:0, text:'Bebe em copo com ajuda sem derramar muito' },
  { id:'a0_10', domain:'autocuidados', rangeIndex:0, text:'Indica desconforto com fralda suja' },
  { id:'a0_11', domain:'autocuidados', rangeIndex:0, text:'Tira meias ou sapatos simples' },
  { id:'a0_12', domain:'autocuidados', rangeIndex:0, text:'Come alimentos sólidos mastigando' },
  { id:'a0_13', domain:'autocuidados', rangeIndex:0, text:'Usa colher com alguma coordenação' },
  { id:'a1_01', domain:'autocuidados', rangeIndex:1, text:'Come com colher com pouca sujeira' },
  { id:'a1_02', domain:'autocuidados', rangeIndex:1, text:'Bebe em copo sem ajuda' },
  { id:'a1_03', domain:'autocuidados', rangeIndex:1, text:'Indica necessidade de ir ao banheiro' },
  { id:'a1_04', domain:'autocuidados', rangeIndex:1, text:'Tira sapatos sem cadarço' },
  { id:'a1_05', domain:'autocuidados', rangeIndex:1, text:'Colabora ao ser vestido e despido' },
  { id:'a1_06', domain:'autocuidados', rangeIndex:1, text:'Lava as mãos com ajuda' },
  { id:'a1_07', domain:'autocuidados', rangeIndex:1, text:'Usa lenço para limpar o nariz com ajuda' },
  { id:'a1_08', domain:'autocuidados', rangeIndex:1, text:'Demonstra controle de esfíncter diurno' },
  { id:'a1_09', domain:'autocuidados', rangeIndex:1, text:'Despe peças simples de roupa' },
  { id:'a1_10', domain:'autocuidados', rangeIndex:1, text:'Usa garfo com ajuda' },
  { id:'a1_11', domain:'autocuidados', rangeIndex:1, text:'Escova os dentes com ajuda' },
  { id:'a1_12', domain:'autocuidados', rangeIndex:1, text:'Dorme a noite toda sem fraldas' },
  { id:'a2_01', domain:'autocuidados', rangeIndex:2, text:'Veste peças simples sozinho' },
  { id:'a2_02', domain:'autocuidados', rangeIndex:2, text:'Usa o banheiro sozinho (com ajuda para higiene)' },
  { id:'a2_03', domain:'autocuidados', rangeIndex:2, text:'Lava as mãos sozinho' },
  { id:'a2_04', domain:'autocuidados', rangeIndex:2, text:'Come com garfo e colher' },
  { id:'a2_05', domain:'autocuidados', rangeIndex:2, text:'Escova os dentes com supervisão' },
  { id:'a2_06', domain:'autocuidados', rangeIndex:2, text:'Tira e coloca sapatos simples' },
  { id:'a2_07', domain:'autocuidados', rangeIndex:2, text:'Serve-se de bebida com pouca ajuda' },
  { id:'a2_08', domain:'autocuidados', rangeIndex:2, text:'Limpa-se após usar o banheiro com ajuda' },
  { id:'a2_09', domain:'autocuidados', rangeIndex:2, text:'Veste e despe casaco simples' },
  { id:'a2_10', domain:'autocuidados', rangeIndex:2, text:'Reconhece e evita situações de perigo simples' },
  { id:'a2_11', domain:'autocuidados', rangeIndex:2, text:'Guarda brinquedos quando solicitado' },
  { id:'a2_12', domain:'autocuidados', rangeIndex:2, text:'Abotoa botões grandes' },
  { id:'a2_13', domain:'autocuidados', rangeIndex:2, text:'Usa zíper simples' },
  { id:'a2_14', domain:'autocuidados', rangeIndex:2, text:'Demonstra controle total de esfíncteres' },
  { id:'a2_15', domain:'autocuidados', rangeIndex:2, text:'Penteia o cabelo com ajuda' },
  { id:'a3_01', domain:'autocuidados', rangeIndex:3, text:'Veste-se completamente sozinho' },
  { id:'a3_02', domain:'autocuidados', rangeIndex:3, text:'Amarra os cadarços com ajuda' },
  { id:'a3_03', domain:'autocuidados', rangeIndex:3, text:'Escova os dentes sozinho' },
  { id:'a3_04', domain:'autocuidados', rangeIndex:3, text:'Usa talheres adequadamente' },
  { id:'a3_05', domain:'autocuidados', rangeIndex:3, text:'Toma banho com supervisão' },
  { id:'a3_06', domain:'autocuidados', rangeIndex:3, text:'Usa o banheiro com total independência' },
  { id:'a3_07', domain:'autocuidados', rangeIndex:3, text:'Reconhece alimentos saudáveis' },
  { id:'a3_08', domain:'autocuidados', rangeIndex:3, text:'Cuida de seus pertences escolares' },
  { id:'a3_09', domain:'autocuidados', rangeIndex:3, text:'Atravessa rua com segurança com adulto' },
  { id:'a3_10', domain:'autocuidados', rangeIndex:3, text:'Conhece seu endereço e telefone' },
  { id:'a3_11', domain:'autocuidados', rangeIndex:3, text:'Distingue situações de perigo' },
  { id:'a3_12', domain:'autocuidados', rangeIndex:3, text:'Organiza sua mochila escolar' },
  { id:'a3_13', domain:'autocuidados', rangeIndex:3, text:'Serve-se à mesa com independência' },
  { id:'a3_14', domain:'autocuidados', rangeIndex:3, text:'Mantém higiene pessoal básica' },
  { id:'a3_15', domain:'autocuidados', rangeIndex:3, text:'Escolhe roupas adequadas ao clima' },
  { id:'a4_01', domain:'autocuidados', rangeIndex:4, text:'Amarra cadarços sozinho' },
  { id:'a4_02', domain:'autocuidados', rangeIndex:4, text:'Toma banho com autonomia' },
  { id:'a4_03', domain:'autocuidados', rangeIndex:4, text:'Prepara lanche simples' },
  { id:'a4_04', domain:'autocuidados', rangeIndex:4, text:'Cuida do próprio material escolar' },
  { id:'a4_05', domain:'autocuidados', rangeIndex:4, text:'Usa transporte público com adulto' },
  { id:'a4_06', domain:'autocuidados', rangeIndex:4, text:'Demonstra noções de segurança pessoal' },
  { id:'a4_07', domain:'autocuidados', rangeIndex:4, text:'Gerencia tempo em atividades rotineiras' },
  { id:'a4_08', domain:'autocuidados', rangeIndex:4, text:'Mantém quarto organizado com supervisão' },
  { id:'a4_09', domain:'autocuidados', rangeIndex:4, text:'Cuida de animais de estimação com ajuda' },
  { id:'a4_10', domain:'autocuidados', rangeIndex:4, text:'Realiza tarefas domésticas simples' },
  { id:'a4_11', domain:'autocuidados', rangeIndex:4, text:'Demonstra hábitos de alimentação saudável' },
  { id:'a4_12', domain:'autocuidados', rangeIndex:4, text:'Reconhece e comunica necessidades de saúde' },
  { id:'a4_13', domain:'autocuidados', rangeIndex:4, text:'Usa dinheiro em compras simples com ajuda' },
  { id:'a4_14', domain:'autocuidados', rangeIndex:4, text:'Demonstra cuidado com a própria segurança' },
  { id:'a4_15', domain:'autocuidados', rangeIndex:4, text:'Cuida da higiene pessoal completa' },
  { id:'a4_16', domain:'autocuidados', rangeIndex:4, text:'Organiza agenda e compromissos simples' },
  { id:'a5_01', domain:'autocuidados', rangeIndex:5, text:'Prepara refeições simples sozinho' },
  { id:'a5_02', domain:'autocuidados', rangeIndex:5, text:'Gerencia rotina diária com autonomia' },
  { id:'a5_03', domain:'autocuidados', rangeIndex:5, text:'Usa transporte com independência adequada' },
  { id:'a5_04', domain:'autocuidados', rangeIndex:5, text:'Realiza compras simples sozinho' },
  { id:'a5_05', domain:'autocuidados', rangeIndex:5, text:'Demonstra responsabilidade com obrigações' },
  { id:'a5_06', domain:'autocuidados', rangeIndex:5, text:'Cuida da saúde e higiene com autonomia' },
  { id:'a5_07', domain:'autocuidados', rangeIndex:5, text:'Organiza e mantém seus pertences' },
  { id:'a5_08', domain:'autocuidados', rangeIndex:5, text:'Demonstra segurança em situações de risco' },
  { id:'a5_09', domain:'autocuidados', rangeIndex:5, text:'Colabora em tarefas domésticas regularmente' },
  { id:'a5_10', domain:'autocuidados', rangeIndex:5, text:'Planeja e executa atividades de lazer' },
  { id:'a5_11', domain:'autocuidados', rangeIndex:5, text:'Demonstra autonomia adequada à idade' },
  { id:'a5_12', domain:'autocuidados', rangeIndex:5, text:'Gerencia dinheiro de mesada simples' },
  { id:'a5_13', domain:'autocuidados', rangeIndex:5, text:'Cuida do ambiente em que vive' },
  { id:'a5_14', domain:'autocuidados', rangeIndex:5, text:'Demonstra iniciativa em resolver problemas' },
  { id:'a5_15', domain:'autocuidados', rangeIndex:5, text:'Usa recursos da comunidade adequadamente' },
  { id:'m0_01', domain:'motor', rangeIndex:0, text:'Sustenta a cabeça quando em posição ventral' },
  { id:'m0_02', domain:'motor', rangeIndex:0, text:'Vira de barriga para cima para barriga para baixo' },
  { id:'m0_03', domain:'motor', rangeIndex:0, text:'Senta com apoio por alguns minutos' },
  { id:'m0_04', domain:'motor', rangeIndex:0, text:'Engatinha ou arrasta pelo chão' },
  { id:'m0_05', domain:'motor', rangeIndex:0, text:'Fica em pé com apoio' },
  { id:'m0_06', domain:'motor', rangeIndex:0, text:'Dá passos laterais apoiado em móveis' },
  { id:'m0_07', domain:'motor', rangeIndex:0, text:'Agarra objetos com preensão palmar' },
  { id:'m0_08', domain:'motor', rangeIndex:0, text:'Usa pinça entre polegar e indicador' },
  { id:'m0_09', domain:'motor', rangeIndex:0, text:'Transfere objeto de uma mão para outra' },
  { id:'m0_10', domain:'motor', rangeIndex:0, text:'Bate dois objetos um contra o outro' },
  { id:'m0_11', domain:'motor', rangeIndex:0, text:'Joga objetos intencionalmente' },
  { id:'m0_12', domain:'motor', rangeIndex:0, text:'Solta objetos voluntariamente' },
  { id:'m0_13', domain:'motor', rangeIndex:0, text:'Empilha dois a três cubos' },
  { id:'m0_14', domain:'motor', rangeIndex:0, text:'Vira páginas de livro grosso' },
  { id:'m0_15', domain:'motor', rangeIndex:0, text:'Caminha com apoio de uma mão' },
  { id:'m0_16', domain:'motor', rangeIndex:0, text:'Fica em pé sozinho por breves momentos' },
  { id:'m0_17', domain:'motor', rangeIndex:0, text:'Dá primeiros passos sozinho' },
  { id:'m0_18', domain:'motor', rangeIndex:0, text:'Sobe degraus com apoio' },
  { id:'m0_19', domain:'motor', rangeIndex:0, text:'Agacha-se para pegar objeto' },
  { id:'m0_20', domain:'motor', rangeIndex:0, text:'Empurra e puxa objetos ao caminhar' },
  { id:'m0_21', domain:'motor', rangeIndex:0, text:'Senta-se no chão sem apoio' },
  { id:'m0_22', domain:'motor', rangeIndex:0, text:'Levanta-se do chão sem apoio' },
  { id:'m0_23', domain:'motor', rangeIndex:0, text:'Caminha com equilíbrio razoável' },
  { id:'m0_24', domain:'motor', rangeIndex:0, text:'Chuta bola grande' },
  { id:'m0_25', domain:'motor', rangeIndex:0, text:'Arremessa bola com as duas mãos' },
  { id:'m0_26', domain:'motor', rangeIndex:0, text:'Rabisca espontaneamente' },
  { id:'m0_27', domain:'motor', rangeIndex:0, text:'Enfia objetos em recipientes' },
  { id:'m0_28', domain:'motor', rangeIndex:0, text:'Vira maçaneta ou tampa de frasco' },
  { id:'m0_29', domain:'motor', rangeIndex:0, text:'Usa colher com alguma coordenação' },
  { id:'m0_30', domain:'motor', rangeIndex:0, text:'Sobe e desce escadas engatinhando' },
  { id:'m0_31', domain:'motor', rangeIndex:0, text:'Corre de forma desajeitada' },
  { id:'m0_32', domain:'motor', rangeIndex:0, text:'Sobe em móveis baixos' },
  { id:'m0_33', domain:'motor', rangeIndex:0, text:'Empilha 4 a 6 cubos' },
  { id:'m0_34', domain:'motor', rangeIndex:0, text:'Vira páginas de livro fino' },
  { id:'m0_35', domain:'motor', rangeIndex:0, text:'Usa tesoura de brinquedo' },
  { id:'m0_36', domain:'motor', rangeIndex:0, text:'Encaixa formas geométricas simples' },
  { id:'m0_37', domain:'motor', rangeIndex:0, text:'Faz bolinhas de massa de modelar' },
  { id:'m0_38', domain:'motor', rangeIndex:0, text:'Salta com os dois pés' },
  { id:'m0_39', domain:'motor', rangeIndex:0, text:'Anda para trás alguns passos' },
  { id:'m0_40', domain:'motor', rangeIndex:0, text:'Desce escadas com apoio de uma mão' },
  { id:'m0_41', domain:'motor', rangeIndex:0, text:'Chuta bola com direção intencional' },
  { id:'m0_42', domain:'motor', rangeIndex:0, text:'Equilibra-se em um pé por 1 segundo' },
  { id:'m0_43', domain:'motor', rangeIndex:0, text:'Copia linha horizontal e vertical' },
  { id:'m0_44', domain:'motor', rangeIndex:0, text:'Usa giz ou lápis com preensão adequada' },
  { id:'m0_45', domain:'motor', rangeIndex:0, text:'Corre com controle e muda de direção' },
  { id:'m1_01', domain:'motor', rangeIndex:1, text:'Corre com boa coordenação' },
  { id:'m1_02', domain:'motor', rangeIndex:1, text:'Salta distância de 30cm' },
  { id:'m1_03', domain:'motor', rangeIndex:1, text:'Desce escadas alternando os pés' },
  { id:'m1_04', domain:'motor', rangeIndex:1, text:'Equilibra-se em um pé por 3 a 5 segundos' },
  { id:'m1_05', domain:'motor', rangeIndex:1, text:'Copia círculo e cruz' },
  { id:'m1_06', domain:'motor', rangeIndex:1, text:'Usa tesoura para cortar linha reta' },
  { id:'m1_07', domain:'motor', rangeIndex:1, text:'Atira e recebe bola' },
  { id:'m1_08', domain:'motor', rangeIndex:1, text:'Anda em linha reta' },
  { id:'m1_09', domain:'motor', rangeIndex:1, text:'Pedala triciclo ou bicicleta com rodinhas' },
  { id:'m1_10', domain:'motor', rangeIndex:1, text:'Faz bolinhas e cobrinhas com massa' },
  { id:'m1_11', domain:'motor', rangeIndex:1, text:'Segura lápis corretamente' },
  { id:'m1_12', domain:'motor', rangeIndex:1, text:'Pula em um pé só' },
  { id:'m1_13', domain:'motor', rangeIndex:1, text:'Sobe e desce escadas sem apoio' },
  { id:'m1_14', domain:'motor', rangeIndex:1, text:'Recorta figuras simples com tesoura' },
  { id:'m1_15', domain:'motor', rangeIndex:1, text:'Copia quadrado e triângulo' },
  { id:'m1_16', domain:'motor', rangeIndex:1, text:'Desenha figura humana com 4 partes' },
  { id:'m1_17', domain:'motor', rangeIndex:1, text:'Anda na ponta dos pés' },
  { id:'m1_18', domain:'motor', rangeIndex:1, text:'Equilibra-se em trave baixa' },
  { id:'m2_01', domain:'motor', rangeIndex:2, text:'Equilibra-se em um pé por 10 segundos' },
  { id:'m2_02', domain:'motor', rangeIndex:2, text:'Pula corda' },
  { id:'m2_03', domain:'motor', rangeIndex:2, text:'Anda de bicicleta sem rodinhas' },
  { id:'m2_04', domain:'motor', rangeIndex:2, text:'Recorta figuras complexas com tesoura' },
  { id:'m2_05', domain:'motor', rangeIndex:2, text:'Copia letras e números' },
  { id:'m2_06', domain:'motor', rangeIndex:2, text:'Nada com apoio' },
  { id:'m2_07', domain:'motor', rangeIndex:2, text:'Joga e recebe bola com uma mão' },
  { id:'m2_08', domain:'motor', rangeIndex:2, text:'Realiza movimentos rítmicos coordenados' },
  { id:'m2_09', domain:'motor', rangeIndex:2, text:'Pula obstáculos baixos' },
  { id:'m2_10', domain:'motor', rangeIndex:2, text:'Escreve nome com letra legível' },
  { id:'m2_11', domain:'motor', rangeIndex:2, text:'Usa ferramentas simples (martelo, chave)' },
  { id:'m3_01', domain:'motor', rangeIndex:3, text:'Escreve com letra cursiva inicial' },
  { id:'m3_02', domain:'motor', rangeIndex:3, text:'Pratica esportes com regras básicas' },
  { id:'m3_03', domain:'motor', rangeIndex:3, text:'Nada ou demonstra habilidades aquáticas' },
  { id:'m3_04', domain:'motor', rangeIndex:3, text:'Demonstra coordenação motora fina refinada' },
  { id:'m3_05', domain:'motor', rangeIndex:3, text:'Realiza atividades físicas com resistência' },
  { id:'m4_01', domain:'motor', rangeIndex:4, text:'Demonstra habilidades motoras globais refinadas' },
  { id:'m4_02', domain:'motor', rangeIndex:4, text:'Pratica esporte ou dança com coordenação' },
  { id:'m4_03', domain:'motor', rangeIndex:4, text:'Usa teclado e mouse com facilidade' },
  { id:'m4_04', domain:'motor', rangeIndex:4, text:'Escreve com fluência e legibilidade' },
  { id:'m4_05', domain:'motor', rangeIndex:4, text:'Demonstra resistência física adequada' },
  { id:'m5_01', domain:'motor', rangeIndex:5, text:'Pratica atividade física regularmente' },
  { id:'m5_02', domain:'motor', rangeIndex:5, text:'Demonstra coordenação motora ampla e fina' },
  { id:'m5_03', domain:'motor', rangeIndex:5, text:'Usa ferramentas e instrumentos com precisão' },
  { id:'m5_04', domain:'motor', rangeIndex:5, text:'Escreve textos com velocidade e legibilidade' },
  { id:'m5_05', domain:'motor', rangeIndex:5, text:'Demonstra equilíbrio e agilidade' },
  { id:'m5_06', domain:'motor', rangeIndex:5, text:'Realiza atividades que exigem força e resistência' },
  { id:'m5_07', domain:'motor', rangeIndex:5, text:'Coordena movimentos complexos em esportes' },
  { id:'m5_08', domain:'motor', rangeIndex:5, text:'Demonstra lateralidade definida' },
  { id:'m5_09', domain:'motor', rangeIndex:5, text:'Usa computador e tecnologia com desenvoltura' },
  { id:'m5_10', domain:'motor', rangeIndex:5, text:'Demonstra cuidado e controle nos movimentos' },
  { id:'m5_11', domain:'motor', rangeIndex:5, text:'Realiza tarefas de motricidade fina com precisão' },
  { id:'m5_12', domain:'motor', rangeIndex:5, text:'Demonstra consciência corporal adequada' },
];

export function getItemsByDomainAndRange(
    domain: PortageItem['domain'],
    rangeIndex: number
): PortageItem[] {
    return PORTAGE_ITEMS.filter(item => item.domain === domain && item.rangeIndex === rangeIndex);
}

export function calculateScoreFromResponses(
    responses: Record<string, ItemResponse>,
    domain: PortageItem['domain'],
    rangeIndex: number
): number {
    const items = getItemsByDomainAndRange(domain, rangeIndex);
    return items.reduce((total, item) => {
        const resp = responses[item.id];
        if (resp === 'sim') return total + 1;
        if (resp === 'ajuda') return total + 0.5;
        return total;
    }, 0);
}
